title: Algorithmic Bias Research
description: We are a group of Data Science students at UPC in Barcelona. We will use this blog to track our study process on the bias found in algorithms, focusing on those used in Machine Translation.
theme: jekyll-theme-slate
